### PR TITLE
Fixed

### PR DESCRIPTION
**Pull request by RutOf**

### CODE REVIEW

**Comment by Fnoberz** [comment]
That's the best driver for us and and we test it ourselves. So if there is no need to mess with Driver to prevent further errors.

**Comment by smithkernel** [comment]
How can I be sure it's safe? for added features Because I'm not sure if it's really safe or not ... I just want an answer.

**Comment by RutOf** [comment]
Hmm, sorry, I just need some Setup 11, hope you understand.

**Comment by Fnoberz** [comment]
No problem and I hope it won't happen again.

**Pull request merged**
