### PR TITLE
Solved many problems as follows:

### PR DESCRIPTION
**Pull request by SamcroBIT**
- S/N number update
- Fixed the issue of Skel that was too big than usual.
- Fixed a problem when Injector and fail (in case of using Injector)
- change from show color > to show address distance / But you can modify it to show the same color as follows:

```h
uint64_t pageoffset = address & ~( ~0ul << PAGE_OFFSET_SIZE );
uint64_t pte = ( ( address >> 12 ) & ( 0x1ffll ) );
uint64_t pt = ( ( address >> 21 ) & ( 0x1ffll ) );
uint64_t pd = ( ( address >> 30 ) & ( 0x1ffll ) );
uint64_t pdp = ( ( address >> 39 ) & ( 0x1ffll ) );
```

### CODE REVIEW

**Comment by Fnoberz** [comment]
**Some people** don't have that much knowledge. that they will be able to check and correct the color lmao

**Comment by SamcroBIT** [comment]
I'm going to add the code to change the button in the game myself " CHANGE " but for now I have to eat first. Come back to start work for you.

**Comment by Fnoberz** [comment]
It's okay, I'll add that command for you. which can be set as a hotkey as well

**Comment by Fnoberz** [comment]
@Pridestike you can send email to me Because I'm not at home right now and it might not be easy to fix. But I will send it to the developer team under my project. let them manage

**Comment by Fnoberz** [comment]
Alright wait me going home.

**Review by Fnoberz — COMMENTED** [review]
5/10 Because in fact, you can modify the code to have smaller instructions. For the convenience of editing

**Comment by slipstream00** [comment]
WHY WOULD YOU SCAM ME? 
Those who can see this comment is lucky, don’t buy private. After you buy, he will block you in all servers.

**Comment by slipstream00** [comment]
> 5/10 Because in fact, you can modify the code to have smaller instructions. For the convenience of editing

So much for beinh legit

**Pull request merged**
